/**
 * Generated by `scripts/gen-entries.mjs` from `games/apps.mjs`. Do not edit.
 *
 * Every arcade game in one map. They share a bundle because a tool's UI
 * resource is bound at registration time, so the single `play` tool cannot
 * swap in a different document per game.
 */
import type { ComponentType } from "react";
import type { AppProps } from "../lib/runtime";
import TwentyQuestions from "../twenty-questions";
import Hangman from "../hangman";
import EmojiRiddle from "../emoji-riddle";
import HigherLower from "../higher-lower";
import WordSearch from "../word-search";
import Breakout from "../breakout";
import Flappy from "../flappy";
import StackTower from "../stack-tower";
import AimTrainer from "../aim-trainer";
import Sudoku from "../sudoku";
import Nonogram from "../nonogram";
import Sokoban from "../sokoban";
import Mastermind from "../mastermind";
import ConnectFour from "../connect-four";
import UltimateTtt from "../ultimate-ttt";
import Blackjack from "../blackjack";
import Battleship from "../battleship";
import Yahtzee from "../yahtzee";

export interface ArcadeEntry {
  name: string;
  title: string;
  blurb: string;
  group: string;
  Component: ComponentType<AppProps>;
}

export const ARCADE_ENTRIES: ArcadeEntry[] = [
  { name: "twenty-questions", title: "20 Questions", blurb: "The model guesses what you are thinking of", group: "Model", Component: TwentyQuestions },
  { name: "hangman", title: "Hangman", blurb: "Themed words, one hint if you beg", group: "Model", Component: Hangman },
  { name: "emoji-riddle", title: "Emoji Riddle", blurb: "Decode films and idioms from emoji", group: "Model", Component: EmojiRiddle },
  { name: "higher-lower", title: "Higher or Lower", blurb: "Which number is bigger, endlessly", group: "Model", Component: HigherLower },
  { name: "word-search", title: "Word Search", blurb: "Find the model's themed words", group: "Model", Component: WordSearch },
  { name: "breakout", title: "Breakout", blurb: "Paddle, bricks, powerups", group: "Arcade", Component: Breakout },
  { name: "flappy", title: "Flappy", blurb: "One tap, many deaths", group: "Arcade", Component: Flappy },
  { name: "stack-tower", title: "Stack Tower", blurb: "Time each drop, the tower narrows", group: "Arcade", Component: StackTower },
  { name: "aim-trainer", title: "Aim Trainer", blurb: "Thirty seconds of targets", group: "Arcade", Component: AimTrainer },
  { name: "sudoku", title: "Sudoku", blurb: "Generated, solvable, four difficulties", group: "Puzzle", Component: Sudoku },
  { name: "nonogram", title: "Nonogram", blurb: "Picross from the model's bitmap", group: "Puzzle", Component: Nonogram },
  { name: "sokoban", title: "Sokoban", blurb: "Push every crate onto a target", group: "Puzzle", Component: Sokoban },
  { name: "mastermind", title: "Mastermind", blurb: "Break the colour code in ten", group: "Puzzle", Component: Mastermind },
  { name: "connect-four", title: "Connect Four", blurb: "Four in a row against minimax", group: "Versus", Component: ConnectFour },
  { name: "ultimate-ttt", title: "Ultimate Tic-Tac-Toe", blurb: "Nine boards, one winner", group: "Versus", Component: UltimateTtt },
  { name: "blackjack", title: "Blackjack", blurb: "Bet, split, double, bust", group: "Versus", Component: Blackjack },
  { name: "battleship", title: "Battleship", blurb: "Sink the fleet before it sinks yours", group: "Versus", Component: Battleship },
  { name: "yahtzee", title: "Yahtzee", blurb: "Five dice, thirteen boxes", group: "Versus", Component: Yahtzee },
];

export const ARCADE_BY_NAME: Record<string, ArcadeEntry> = Object.fromEntries(
  ARCADE_ENTRIES.map((e) => [e.name, e]),
);
