/**
 * Generates the mechanical scaffolding around each game so nobody hand-writes
 * it thirty-two times:
 *
 *  - `entries/<hero>.html` and `entries/arcade.html`, the Vite entry documents
 *  - `src/<hero>/main.tsx`, which mounts the hero's component
 *  - `src/arcade/main.tsx` and `src/arcade/games.generated.ts`, the dispatcher
 *    and its map of arcade game name to component
 *  - a placeholder `src/<game>/index.tsx` for any game not written yet, so the
 *    tree always type-checks and always builds
 *
 * Everything here is derived from `games/apps.mjs`. Generated files are
 * rewritten on every run EXCEPT placeholders, which are only ever created when
 * missing, so a real implementation is never clobbered.
 *
 * Run directly with `node scripts/gen-entries.mjs`, or as part of the build.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { ARCADE_GAMES, ALL_APPS, ALL_GAMES, ENTRY_DIR, HERO_GAMES } from "../games/apps.mjs";
import { ICON_ATTRS, iconFor } from "../games/icons.mjs";

const root = process.cwd();
const src = path.join(root, "src");
const entryDir = path.join(root, ENTRY_DIR);

/** `stack-tower` becomes `StackTower`; `2048` becomes `Game2048`. */
export function ident(name) {
  const pascal = name
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("");
  return /^[0-9]/.test(pascal) ? `Game${pascal}` : pascal;
}

/** Write only when the content actually changed, to keep Vite's watcher quiet. */
async function writeIfChanged(file, content) {
  try {
    if ((await fs.readFile(file, "utf-8")) === content) return false;
  } catch {
    // Missing file, fall through and write it.
  }
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, content, "utf-8");
  return true;
}

/** Create only when absent. Used for placeholders we must never overwrite. */
async function writeIfMissing(file, content) {
  try {
    await fs.access(file);
    return false;
  } catch {
    await fs.mkdir(path.dirname(file), { recursive: true });
    await fs.writeFile(file, content, "utf-8");
    return true;
  }
}

const htmlEntry = (title, entryPath) => `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="color-scheme" content="light dark">
  <title>${title}</title>
  <link rel="stylesheet" href="/src/global.css">
</head>
<body>
  <div id="root"></div>
  <script type="module" src="${entryPath}"></script>
</body>
</html>
`;

const heroMain = (name, title) => `/**
 * Generated entry for ${title}. Do not edit; change \`src/${name}/index.tsx\`
 * or \`games/apps.mjs\` and re-run \`node scripts/gen-entries.mjs\`.
 */
import { renderApp } from "../lib/runtime";
import Game from "./index";

renderApp({ name: "${title}", version: "1.0.0" }, Game);
`;

const placeholder = (name, title) => `/**
 * ICEBOX-STUB
 *
 * Placeholder for ${title}. Replace this whole file with the real game. It
 * exists so the tree type-checks and the arcade bundle builds while the other
 * games are still being written.
 *
 * Build it against the shared shell in \`src/lib/game.tsx\`: \`useGameLoop\` or
 * \`useFrameLoop\`, \`useDirectionKeys\`, \`useSwipe\`, \`GameFrame\`,
 * \`GameHeader\`, \`Overlay\`, \`StandardControls\`, \`useBest\`,
 * \`useGameOverReport\` and \`useSeed\`.
 */
import { GameHeader, Notice } from "../lib/game";
import type { AppProps } from "../lib/runtime";

export default function ${ident(name)}({ runtime }: AppProps) {
  return (
    <>
      <GameHeader title="${title}" hint={runtime.standalone ? "Standalone preview" : undefined} />
      <Notice>This game has not been built yet.</Notice>
    </>
  );
}
`;

function arcadeMap() {
  const imports = ARCADE_GAMES.map((g) => `import ${ident(g.name)} from "../${g.name}";`).join("\n");
  const entries = ARCADE_GAMES.map(
    (g) =>
      `  { name: ${JSON.stringify(g.name)}, title: ${JSON.stringify(g.title)}, blurb: ${JSON.stringify(
        g.blurb,
      )}, group: ${JSON.stringify(g.group ?? "Arcade")}, Component: ${ident(g.name)} },`,
  ).join("\n");

  // The picker lists everything the server can open, not just what this bundle
  // holds, so `icon` and `kind` come along for the ride. An entry the bundle
  // cannot mount is opened by asking the model for it instead.
  const catalogue = ALL_APPS.map(
    (a) =>
      `  { name: ${JSON.stringify(a.name)}, title: ${JSON.stringify(a.title)}, blurb: ${JSON.stringify(
        a.blurb,
      )}, group: ${JSON.stringify(a.group ?? "Mini apps")}, kind: ${JSON.stringify(
        a.kind,
      )}, icon: ${JSON.stringify(iconFor(a.name))} },`,
  ).join("\n");

  return `/**
 * Generated by \`scripts/gen-entries.mjs\` from \`games/apps.mjs\`. Do not edit.
 *
 * Two things:
 *
 *  - \`ARCADE_ENTRIES\`, the games this bundle can actually mount. They share a
 *    bundle because a tool's UI resource is bound at registration time, so the
 *    single \`play\` tool cannot swap in a different document per game.
 *  - \`CATALOGUE\`, every app the server can open. The picker lists all of them,
 *    because "what can I play" should answer with the whole thing rather than
 *    only the part that happens to live here. Anything without a Component is
 *    opened by asking the model to call that app's own tool.
 *
 * \`icon\` is inline SVG markup from \`games/icons.mjs\`, a build-time constant.
 * It is never model or user input, which is what makes it safe to inject.
 */
import type { ComponentType } from "react";
import type { AppProps } from "../lib/runtime";
${imports}

export interface ArcadeEntry {
  name: string;
  title: string;
  blurb: string;
  group: string;
  Component: ComponentType<AppProps>;
}

export interface CatalogueEntry {
  name: string;
  title: string;
  blurb: string;
  group: string;
  kind: "app" | "hero" | "arcade";
  /** Inline SVG markup, a build-time constant from games/icons.mjs. */
  icon: string;
}

export const ARCADE_ENTRIES: ArcadeEntry[] = [
${entries}
];

export const ARCADE_BY_NAME: Record<string, ArcadeEntry> = Object.fromEntries(
  ARCADE_ENTRIES.map((e) => [e.name, e]),
);

export const CATALOGUE: CatalogueEntry[] = [
${catalogue}
];

export const ICON_ATTRS =
  ${JSON.stringify(ICON_ATTRS)};
`;
}

const arcadeMain = `/**
 * Generated entry for the arcade bundle. Do not edit; change
 * \`src/arcade/index.tsx\` instead.
 */
import { renderApp } from "../lib/runtime";
import Arcade from "./index";

renderApp({ name: "Icebox Arcade", version: "1.0.0" }, Arcade);
`;

async function main() {
  const wrote = [];
  const created = [];

  for (const hero of HERO_GAMES) {
    if (
      await writeIfChanged(
        path.join(entryDir, `${hero.name}.html`),
        htmlEntry(hero.title, `/src/${hero.name}/main.tsx`),
      )
    )
      wrote.push(`${ENTRY_DIR}/${hero.name}.html`);
    if (await writeIfChanged(path.join(src, hero.name, "main.tsx"), heroMain(hero.name, hero.title)))
      wrote.push(`src/${hero.name}/main.tsx`);
  }

  if (await writeIfChanged(path.join(entryDir, "arcade.html"), htmlEntry("Icebox Arcade", "/src/arcade/main.tsx")))
    wrote.push(`${ENTRY_DIR}/arcade.html`);
  if (await writeIfChanged(path.join(src, "arcade", "main.tsx"), arcadeMain)) wrote.push("src/arcade/main.tsx");
  if (await writeIfChanged(path.join(src, "arcade", "games.generated.ts"), arcadeMap()))
    wrote.push("src/arcade/games.generated.ts");

  for (const game of ALL_GAMES) {
    if (await writeIfMissing(path.join(src, game.name, "index.tsx"), placeholder(game.name, game.title)))
      created.push(`src/${game.name}/index.tsx`);
  }

  console.log(`gen-entries: ${wrote.length} generated, ${created.length} placeholders created`);
  if (created.length) console.log(`  placeholders: ${created.map((f) => f.split("/")[1]).join(", ")}`);
}

await main();
