/**
 * Generates the two app listings from the manifest.
 *
 *  - `index.html`, the dev launcher Vite opens at `/`. Written whole, since it
 *    exists only for local preview.
 *  - the catalogue section of `public/index.html`, the page the server serves
 *    at `/`. Only the marked region is replaced, so the hero, the connect
 *    instructions and the footer stay hand-written.
 *
 * Both listed eight apps long after thirty-two shipped, which is what hand-editing
 * two parallel lists always ends up doing. Deriving them from
 * `games/apps.mjs` means adding a game updates both pages for free.
 *
 * Arcade games have no HTML entry of their own, since they share `arcade.html`,
 * so the launcher deep-links them with `?game=<name>`, which the arcade
 * dispatcher honours in standalone preview.
 *
 * Run with `npm run gen:pages`, or as part of `npm run gen`.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { ARCADE_GAMES, HERO_GAMES, ORIGINAL_APPS } from "../games/apps.mjs";
import { ICON_ATTRS, iconFor } from "../games/icons.mjs";

const root = process.cwd();

/** Where a given app opens in standalone preview. */
const previewHref = (app) =>
  app.kind === "arcade" ? `/arcade.html?game=${app.name}` : `/${app.name}.html`;

/**
 * Sections in display order. The originals split from the games because they
 * are tools rather than things you play, which is the distinction a visitor
 * actually cares about.
 */
const MINI_APPS = ORIGINAL_APPS.filter((a) => !["wordle", "snake"].includes(a.name));
const CLASSICS = ORIGINAL_APPS.filter((a) => ["snake", "wordle"].includes(a.name));

const SECTIONS = [
  {
    id: "apps",
    title: "Mini apps",
    note: "Small tools, one call each.",
    apps: MINI_APPS,
  },
  {
    id: "games",
    title: "Games with their own tool",
    note: "Ask for these by name.",
    apps: [...CLASSICS, ...HERO_GAMES],
  },
  {
    id: "arcade",
    title: "The arcade",
    note: "Eighteen more behind the play tool. Ask for one by name, or open the picker.",
    apps: ARCADE_GAMES,
  },
];

const svg = (name) => `<svg ${ICON_ATTRS}>${iconFor(name)}</svg>`;
const escape = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const TOTAL = ORIGINAL_APPS.length + HERO_GAMES.length + ARCADE_GAMES.length;

/* ------------------------------------------------------------------ */
/* Dev launcher                                                        */
/* ------------------------------------------------------------------ */

function launcher() {
  const sections = SECTIONS.map(
    (section) => `      <section class="group">
        <h2>${section.title} <span class="count">${section.apps.length}</span></h2>
        <p class="note">${escape(section.note)}</p>
        <ul class="grid">
${section.apps
  .map(
    (app) => `          <li><a class="app" href="${previewHref(app)}">
            <span class="ic">${svg(app.name)}</span>
            <span class="name">${escape(app.title)}</span>
            <small>${escape(app.blurb)}</small>
          </a></li>`,
  )
  .join("\n")}
        </ul>
      </section>`,
  ).join("\n\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="color-scheme" content="light dark">
  <title>Icebox preview launcher</title>
  <link rel="stylesheet" href="/src/global.css">
  <style>
    /* Generated by scripts/gen-pages.mjs. Edit that, not this. */
    body { font-family: var(--font-sans); }
    .wrap { max-width: 940px; margin: 0 auto; padding: 32px 20px 56px; }
    h1 { font-size: 1.6rem; margin: 0 0 4px; }
    .lead { margin: 0 0 28px; color: var(--color-text-secondary); font-size: 0.9rem; max-width: 62ch; }
    .group { margin: 0 0 30px; }
    .group h2 {
      display: flex; align-items: center; gap: 8px;
      margin: 0 0 2px; font-size: 0.72rem; font-weight: 700;
      letter-spacing: 0.14em; text-transform: uppercase;
      color: var(--color-text-secondary);
    }
    .count {
      font-size: 0.68rem; letter-spacing: 0; padding: 1px 7px; border-radius: 999px;
      background: var(--color-background-secondary); border: 1px solid var(--color-border);
    }
    .note { margin: 0 0 12px; color: var(--color-text-secondary); font-size: 0.82rem; }
    .grid {
      list-style: none; margin: 0; padding: 0;
      display: grid; gap: 10px;
      grid-template-columns: repeat(auto-fill, minmax(190px, 1fr));
    }
    a.app {
      display: grid;
      grid-template-columns: auto 1fr;
      column-gap: 11px; row-gap: 1px;
      align-items: center;
      height: 100%;
      padding: 13px 15px;
      border-radius: 12px;
      text-decoration: none;
      color: var(--color-text-primary);
      background: var(--color-background-secondary);
      border: 1px solid var(--color-border);
    }
    a.app:hover { border-color: var(--color-ring-primary); }
    a.app:focus-visible { outline: 2px solid var(--color-ring-primary); outline-offset: 2px; }
    .ic { grid-row: 1 / 3; display: inline-flex; color: var(--color-accent); }
    .ic svg { width: 25px; height: 25px; }
    .name { font-weight: 600; font-size: 0.92rem; }
    a.app small { grid-column: 2; color: var(--color-text-secondary); font-size: 0.76rem; line-height: 1.35; }
  </style>
</head>
<body>
  <div class="wrap">
    <h1>Icebox local preview</h1>
    <p class="lead">
      All ${TOTAL} apps in standalone preview mode, no MCP host needed. Arcade games
      share one bundle, so they open through <code>arcade.html?game=</code>.
    </p>

${sections}
  </div>
</body>
</html>
`;
}

/* ------------------------------------------------------------------ */
/* Landing page catalogue                                              */
/* ------------------------------------------------------------------ */

function catalogue() {
  return SECTIONS.map(
    (section) => `      <div class="group-head">
        <h2 class="group-title">${section.title}</h2>
        <span class="group-count">${section.apps.length}</span>
      </div>
      <p class="group-note">${escape(section.note)}</p>
      <section class="grid">
${section.apps
  .map(
    (app) => `        <div class="card">
          <span class="icon">${svg(app.name)}</span>
          <b>${escape(app.title)}</b><span>${escape(app.blurb)}</span>
        </div>`,
  )
  .join("\n")}
      </section>`,
  ).join("\n\n");
}

const START = "<!-- APPS:START -->";
const END = "<!-- APPS:END -->";

async function writeLanding() {
  const file = path.join(root, "public", "index.html");
  const html = await fs.readFile(file, "utf-8");
  const from = html.indexOf(START);
  const to = html.indexOf(END);
  if (from === -1 || to === -1) {
    console.error(`gen-pages: ${START} / ${END} markers missing from public/index.html`);
    process.exit(1);
  }
  const next =
    html.slice(0, from + START.length) +
    "\n" +
    catalogue() +
    "\n      " +
    html.slice(to);
  if (next === html) return false;
  await fs.writeFile(file, next, "utf-8");
  return true;
}

async function writeIfChanged(file, content) {
  try {
    if ((await fs.readFile(file, "utf-8")) === content) return false;
  } catch {
    // Missing, fall through.
  }
  await fs.writeFile(file, content, "utf-8");
  return true;
}

const wroteLauncher = await writeIfChanged(path.join(root, "index.html"), launcher());
const wroteLanding = await writeLanding();

console.log(
  `gen-pages: ${TOTAL} apps listed. launcher ${wroteLauncher ? "updated" : "unchanged"}, landing ${wroteLanding ? "updated" : "unchanged"}`,
);
